# -*- coding: utf-8 -*-
"""GenAI_Practical1_29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARdlhxqfbjPSxof7ouKtKlJyOaa6geQy
"""

# text representation using NLP technique
# scenario
# A company want to classify customer feedback into machine readable vector using One hot encoding , bag of words

from sklearn.feature_extraction.text import CountVectorizer

# Text Representation using NLP Techniques
# One-Hot Encoding and Bag of Words

from sklearn.feature_extraction.text import CountVectorizer

# Customer feedback
feedback = [
    "product is excellent",
    "product is good",
    "product is bad",
    "excellent product"
]

# -------------------------------
# 1. One-Hot Encoding
# -------------------------------

words = sorted(set(" ".join(feedback).lower().split()))

print("Vocabulary:")
print(words)

print("\nOne-Hot Encoding:")

for sentence in feedback:
    sentence_words = sentence.lower().split()
    vector = [1 if word in sentence_words else 0 for word in words]
    print(sentence, "->", vector)


# -------------------------------
# 2. Bag of Words
# -------------------------------

vectorizer = CountVectorizer()

bow_matrix = vectorizer.fit_transform(feedback)

print("\nBag of Words Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nBag of Words Vectors:")
print(bow_matrix.toarray())