# -*- coding: utf-8 -*-
"""GenAi_Practical5_29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNyPibsaai5dWA6coahLgaZjMK9FJkU-
"""

# A company want to automate its customer service by translating queries from english to hindi. Build a simple english to hindi translation modle using encoder  decoder arcitecture with keras

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense

# 1. Sample English-Hindi dataset
english = [
    "hello", "how are you", "good morning",
    "thank you", "what is your name",
    "i am fine", "good night", "please help me",
    "where are you", "welcome"
]

hindi = [
    "नमस्ते", "आप कैसे हैं", "सुप्रभात",
    "धन्यवाद", "आपका नाम क्या है",
    "मैं ठीक हूँ", "शुभ रात्रि", "कृपया मेरी मदद करें",
    "आप कहाँ हैं", "स्वागत है"
]

# Add start and end tokens for the decoder
hindi_input = ["<start> " + s for s in hindi]
hindi_output = [s + " <end>" for s in hindi]

# 2. Tokenization
en_tokenizer = Tokenizer()
en_tokenizer.fit_on_texts(english)

hi_tokenizer = Tokenizer(filters='')
hi_tokenizer.fit_on_texts(hindi_input + hindi_output)

en_seq = en_tokenizer.texts_to_sequences(english)
hi_in_seq = hi_tokenizer.texts_to_sequences(hindi_input)
hi_out_seq = hi_tokenizer.texts_to_sequences(hindi_output)

max_en = max(len(s) for s in en_seq)
max_hi = max(len(s) for s in hi_in_seq + hi_out_seq)

encoder_data = pad_sequences(en_seq, maxlen=max_en, padding='post')
decoder_data = pad_sequences(hi_in_seq, maxlen=max_hi, padding='post')
target_data = pad_sequences(hi_out_seq, maxlen=max_hi, padding='post')

# 3. Vocabulary sizes
en_vocab = len(en_tokenizer.word_index) + 1
hi_vocab = len(hi_tokenizer.word_index) + 1

# 4. Encoder
encoder_inputs = Input(shape=(max_en,))
encoder_embedding = Embedding(en_vocab, 64)(encoder_inputs)
_, state_h, state_c = LSTM(
    128, return_state=True
)(encoder_embedding)

encoder_states = [state_h, state_c]

# 5. Decoder
decoder_inputs = Input(shape=(max_hi,))
decoder_embedding_layer = Embedding(hi_vocab, 64)
decoder_embedding = decoder_embedding_layer(decoder_inputs)

decoder_lstm = LSTM(128, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(
    decoder_embedding, initial_state=encoder_states
)

decoder_dense = Dense(hi_vocab, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

# 6. Build and train model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(
    [encoder_data, decoder_data],
    np.expand_dims(target_data, -1),
    epochs=300,
    verbose=0
)

print("Model training completed!")

# 7. Translation function
encoder_model = Model(encoder_inputs, encoder_states)

state_input_h = Input(shape=(128,))
state_input_c = Input(shape=(128,))
decoder_states_inputs = [state_input_h, state_input_c]

decoder_emb2 = decoder_embedding_layer(decoder_inputs)
decoder_out2, state_h2, state_c2 = decoder_lstm(
    decoder_emb2, initial_state=decoder_states_inputs
)
decoder_out2 = decoder_dense(decoder_out2)

decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_out2, state_h2, state_c2]
)

def translate(sentence):
    seq = en_tokenizer.texts_to_sequences([sentence.lower()])
    seq = pad_sequences(seq, maxlen=max_en, padding='post')

    states = encoder_model.predict(seq, verbose=0)
    start_id = hi_tokenizer.word_index['<start>']
    end_id = hi_tokenizer.word_index['<end>']

    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = start_id
    result = []

    for _ in range(max_hi):
        output, h, c = decoder_model.predict(
            [target_seq] + states, verbose=0
        )
        word_id = int(np.argmax(output[0, -1, :]))

        if word_id == 0 or word_id == end_id:
            break

        result.append(hi_tokenizer.index_word.get(word_id, ''))
        target_seq[0, 0] = word_id
        states = [h, c]

    return " ".join(result)

# 8. User Input Translation
sentence = input("Enter an English sentence: ")

translated_text = translate(sentence.lower())

print("English:", sentence)
print("Hindi:", translated_text)