# -*- coding: utf-8 -*-
"""GenAI_Practical2_29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sp0A2ae9tp6xaNnbuv2SZjdEMPyvKVhx
"""

# sentiment anaysis using ANN

# an e commerce website want to identify positive and negative product review automatically . Develop a simple ANN based sentiment classifier

# ============================================================
# PRACTICAL 2
# Transfer Learning for Text Classification using BERT
# Classes: Politics, Sport, Technology
# ============================================================

# Step 1: Install Required Libraries
!pip install -q transformers datasets evaluate accelerate

# Step 2: Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

import evaluate


# ============================================================
# Step 3: Load Dataset
# ============================================================

df = pd.read_csv("/content/bbc-text.csv")

print("First 5 rows:")
print(df.head())


# ============================================================
# Step 4: Explore Dataset
# ============================================================

print("\nDataset Shape:")
print(df.shape)

print("\nCategory Counts:")
print(df["category"].value_counts())


# Keep only Sport, Politics and Tech
df = df[df["category"].isin(["sport", "politics", "tech"])]

print("\nSelected Category Counts:")
print(df["category"].value_counts())


# ============================================================
# Step 5: Convert Categories into Numerical Labels
# ============================================================

label_mapping = {
    "politics": 0,
    "sport": 1,
    "tech": 2
}

df["label"] = df["category"].map(label_mapping)

print("\nDataset with Labels:")
print(df.head())


# ============================================================
# Step 6: Split Dataset
# ============================================================

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

print("\nTraining Data:", train_df.shape)
print("Testing Data:", test_df.shape)


# ============================================================
# Step 7: Convert to Hugging Face Dataset
# ============================================================

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)


# ============================================================
# Step 8: Load Pre-trained BERT Tokenizer
# ============================================================

tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)


# ============================================================
# Step 9: Tokenize Dataset
# ============================================================

def tokenize_function(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )


train_dataset = train_dataset.map(tokenize_function)
test_dataset = test_dataset.map(tokenize_function)


# ============================================================
# Step 10: Convert Dataset to PyTorch Format
# ============================================================

train_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

test_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)


# ============================================================
# Step 11: Load Pre-trained BERT Model
# ============================================================

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=3
)


# ============================================================
# Step 12: Load Accuracy Metric
# ============================================================

accuracy = evaluate.load("accuracy")


# ============================================================
# Step 13: Define Evaluation Function
# ============================================================

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    predictions = np.argmax(predictions, axis=1)

    return accuracy.compute(
        predictions=predictions,
        references=labels
    )


# ============================================================
# Step 14: Define Training Parameters
# ============================================================

training_args = TrainingArguments(
    output_dir="./results",

    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    num_train_epochs=3,

    weight_decay=0.01,

    logging_steps=20,

    load_best_model_at_end=True
)


# ============================================================
# Step 15: Create Trainer
# ============================================================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)


# ============================================================
# Step 16: Train the Model
# ============================================================

trainer.train()


# ============================================================
# Step 17: Evaluate the Model
# ============================================================

results = trainer.evaluate()

print("\nEvaluation Results:")
print(results)


# ============================================================
# Step 18: Predict a New News Article
# ============================================================

news = "The government announced a new education policy today."

inputs = tokenizer(
    news,
    return_tensors="pt",
    truncation=True,
    padding=True
)

# Move inputs to same device as model
inputs = {key: value.to(model.device)
          for key, value in inputs.items()}

outputs = model(**inputs)

prediction = outputs.logits.argmax(dim=1).item()


# Convert numerical label back to category
labels = {
    0: "Politics",
    1: "Sport",
    2: "Technology"
}

print("\nNews Article:")
print(news)

print("\nPredicted Category:", labels[prediction])